### ISSUE TITLE
The method `getByTag` does not work for Customer or ExternalAccount objects

### ISSUE THREAD

**Issue by jramnani** [socialmoney/corepro-sdk-java#2]
For the domain objects, `Customer` and `ExternalAccount`, the method `getByTag` throws an error.

The error is:

```
Caused by: java.util.IllegalFormatConversionException: d != java.lang.String
    at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
    at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
    at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
    at java.util.Formatter.format(Formatter.java:2520)
    at java.util.Formatter.format(Formatter.java:2455)
    at java.lang.String.format(String.java:2940)
    at io.corepro.sdk.ExternalAccount.getByTag(ExternalAccount.java:105)
    at io.corepro.sdk.ExternalAccount.getByTag(ExternalAccount.java:99)
    at com.bmo.benjamins.service.CoreProServiceWrapperImpl.verifySourceAccount(CoreProServiceWrapperImpl.java:107)
    at com.bmo.benjamins.service.CoreProFundService.verifySourceAccount(CoreProFundService.java:78)
```

I notice in the method signatures that the `getByTag` functions take an integer, `customerId`, in addition to a Tag.

https://github.com/socialmoney/corepro-sdk-java/blob/master/io.corepro/src/io/corepro/sdk/Customer.java#L130

My understanding is that the purpose of `getByTag` is that it should not require the Customer's ID.  Also, the API documentation shows only `tag` as a required field.
https://docs.corepro.io/api/customer/getbytag

I've noticed this issue with `Customer` and `ExternalAccount` objects, but I haven't checked to see if there are other domain objects affected.

**Comment by brockweaver** [comment]
Thank you for reporting this.  There was definitely a bug in the Customer class; it should not require customerId for getByTag or getByEmail.  This has been addressed and the fix is now available.

However, the ExternalAccount and Account classes do require customerId as the first parameter (and externalaccount.tag / account.tag as the second).  This is a sanity check to ensure that the external account / account denoted by the tag is tied to the provided customer.

While a unique key from the client system can be stored in our customer.tag (or account.tag or externalaccount.tag), most routes still require our internal keys to use them effectively.  For instance, /transfer/create requires all the integer Ids to function properly.

The "normal" use case we've seen is this:

1. User logs into the client system.  
2. Client code calls /customer/getByTag.  This contains a lot of data, including all relevant CorePro Id's (customerId, accountId's, externalAccountId's, etc), but really the only piece of information that needs to be retained (at least temporarily) is the customerId.  It is required by practically every other route in the API.  Most clients tend to permanently associate customerId to the user representation in their system, as the customerId value will never change for a given user.  Some clients simply cache the customerId into a session or cookie and re-fetch it via customer/getByTag when it has expired.
3. Suppose a user wants to view detail about an account.  Client code calls /account/getByTag passing the customerId from step 2 along with the unique key from the client system for that account as the tag, assuming the client system keeps any account information in your system at all.

CustomerId is a very central concept to CorePro and is used extensively throughout our internal indexing and code.  

Please let us know if passing only tags for any route is something that would give considerable lift and we can revisit our API surface to see if that is possible to support and still retain our performance targets.

Thank you again for the bug report!

**Comment by jramnani** [comment]
Thanks for the background on API usage.  Much obliged.  Closing this issue since the original bug I reported has been fixed.
